---

- name: "Check if already registered"
  lineinfile:
    name: /etc/gitlab-runner/config.toml
    line: '  name = "{{ runner.name }}"'
    state: present
  check_mode: yes
  register: conf

- name: 'Register runner "{{ runner.name }}"'
  command: >
    gitlab-runner register
    --non-interactive
    --url '{{ runner.coordinator_url }}'
    --registration-token '{{ gitlab_runner_registration_token }}'
    --description '{{ runner.name }}'
    --tag-list '{{ runner.tags | join(",") }}'
    --executor '{{ runner.executor }}'
    --limit '{{ runner.concurrency }}'
    --locked='{{ runner.locked | default(false) }}'
    {% for env_var in gitlab_runner_env_vars %}
    --env '{{ env_var }}'
    {% endfor %}
    {% if runner.executor == 'docker' %}
    --docker-image '{{ runner.docker_image }}'
    {% endif %}
  when: conf.changed

...